### PR TITLE
Better checks for Changelog entries

### LINKED ISSUE #76: improve check changelog feature
we're using pkgmt to check whether the changelog has [been modified](https://github.com/ploomber/jupysql/blob/ceaa8b8633647813e88dee8e972f8b883596a8e8/.github/workflows/ci.yaml#L68)

however, the current implementation only checks if there has been any change (e.g., adding a newline will pass)

we should improve this feature by checking if the changelog has modifications in the latest section of the file (by looking at main/master)

note that the file different must be computed with respect to the main/master branch, see this code for an [example](https://github.com/ploomber/pkgmt/blob/main/src/pkgmt/fail_if_modified.py)

for example, if the latest section in main is `0.10.0dev`

- PASS: if the changelog in the PR modifies the contents of the `0.10.0dev` section
- FAIL: if there are changes in a section other than `0.10.0dev`
- FAIL: if there is no `0.10.0dev` section
- FAIL: if the `0.10.0dev` has changed but the changes are only whitespace

we already have some code that parses [md files](https://github.com/ploomber/pkgmt/blob/3ce3149f06cc734109dc4a3072b996b3eb8bfb47/src/pkgmt/cli.py#L63), this can help as a starting point.

### PR DESCRIPTION
**Pull request by neelasha23**
Closes #76

### CODE REVIEW

**Comment by neelasha23** [comment]
Please review @edublancas

**Comment by neelasha23** [comment]
[Fixed](https://github.com/ploomber/pkgmt/pull/77/commits/edaa5ba37ef41740a9721afeceb20ca06f9e4f83) the bug that @bryannho mentioned. here's the [commit](https://github.com/ploomber/dummy/pull/66/commits/9b1ddd0b3332d4139ae02bfa2b34aeaf3893a985) and the [check](https://github.com/ploomber/dummy/actions/runs/7963545746/job/21739359433)

Please review again

@bryannho @edublancas

**Comment by edublancas** [comment]
@bryannho don't forget to perform reviews, remember that we have a 24 hours SLA

**Review by bryannho — APPROVED** [review]
@neelasha23 @edublancas tested, bug fixed. looks good to me!

**Review by edublancas — APPROVED** [review]

**Review by edublancas — APPROVED** [review]

**Pull request merged**
